### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by conradKE** [opensource254/website-proposal#5]
hii inaeza wekwa aje kwa opensource official site ?

**Comment by StanleyMasinde** [comment]
You mean like in a dev subdomain?

**Comment by conradKE** [comment]
i mean hizo changes za ui

**Comment by conradKE** [comment]
https://opensource254.github.io/website-proposal/

**Comment by StanleyMasinde** [comment]
> https://opensource254.github.io/website-proposal/

Si changes ziko hapa. The main website is in a separate repository. Au unamean aje?
